wall: fix calloc cal [-Werror=calloc-transposed-args]
term-utils/wall.c:143:37: error: xcalloc sizes specified with sizeof in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  143 |         buf->groups = xcalloc(sizeof(*buf->groups), buf->ngroups);
      |                                     ^
term-utils/wall.c:143:37: note: earlier argument should specify number of elements, later size of each element

Signed-off-by: Karel Zak <kzak@redhat.com>
(cherry picked from commit 07f0f0f5bd1e5e2268257ae1ff6d76a9b6c6ea8b)