mount: s/MOUNTED/_PATH_MOUNTED/
no longer use deprecated alias.
clears a useless compile error when compiling against klibc:
mount.c:995: error: `MOUNTED' undeclared (first use in this function)

Signed-off-by: maximilian attems <max@stro.at>