mount: fix build
With the new build changes when libmount is not defined the compilation breaks:

fstab.c:440: undefined reference to `streq_except_trailing_slash'
collect2: ld returned 1 exit status
make[2]: *** [mtab_lock_test] Error 1
make[2]: Leaving directory `/home/dave/projects/ut/mount'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dave/projects/ut'
make: *** [all] Error 2

This patch adds strutils to the fstab.c rule.

Signed-off-by: Davidlohr Bueso <dave@gnu.org>