{configure.ac,meson.build}: conditionally build {enosys,setpriv} if seccomp is present #3280
misc-utils/enosys.c:25:27: fatal error: linux/seccomp.h: No such file or directory
 #include <linux/seccomp.h>

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
(cherry picked from commit 8de1ec203b0fbf86ae67b1ac18ba094d36b6a34a)